[package]
name = "delaunay"
version = "0.1.0"
edition = "2021"

[lib]
name = "delaunay"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "delaunay_app"
path = "src/main.rs"

[dependencies]
wasm-bindgen = "0.2.84"
js-sys = "0.3.61"